version: 0.2

env:
  variables:
    AWS_REGION: "eu-central-1"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo building images...
      - docker pull nginx
      - docker images
      - docker tag nginx:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:latest
      -
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:latest
      - printf '{"ImageURI":"'${AWS_ACCOUNT_ID}'.dkr.ecr.'${AWS_REGION}'.amazonaws.com/nginx:latest"}' > ../imageDetail.json
artifacts:
  files:
    #- appspec.yml
    #- taskdef.json
    - imageDetail.json
